import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/app/components/theme-provider";
import { cn } from "@/lib/utils"; // Helper function to combine class names if needed

// Define the custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
  title: "My attendence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Avoid manually setting class or style for theme */}
      <body className={cn(geistSans.variable, geistMono.variable)}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system" // Set to "system" for dynamic theme or choose "light" / "dark"
          enableSystem
          disableTransitionOnChange
        > */}
          {children}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
